#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Taxman\Command\Acsf;
use Taxman\Command\Multisite;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new Multisite\ModuleDebtCommand());
$application->add(new Multisite\ModuleListCommand());
$application->add(new Acsf\ModuleDebtCommand());
$application->add(new Acsf\ModuleListCommand());
$application->add(new Acsf\SiteListCommand());
$application->add(new Acsf\SiteModulesCommand());
$application->run();
