#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Taxman\Command;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new Command\AcsfModuleDebtCommand());
$application->add(new Command\AcsfModuleListCommand());
$application->add(new Command\AcsfSiteListCommand());
$application->run();
